version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./build:/usr/app/build:rw
      - ./public:/usr/app/public:ro
      - ./src:/usr/app/src:ro
    command: npm run build
    #
    # prod:
    #   build:
    #     context: .
    #     dockerfile: Dockerfile.prod
    #   ports:
    #     - 80:80
