version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./build:/usr/app/build

  prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - 80:80
