name: Docker CI
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Run Docker Compose
        run: docker-compose up --build

      - name: Compress Data
        run: zip deploy.zip ./build/ ./Dockerfile

      - name: List Items
        run: |
          pwd
          ls
